// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3C3WwzolDa9USm2I6Uttp2glZNBWXygg',
    appId: '1:1011708052725:android:374efad6b816385ea4f1bc',
    messagingSenderId: '1011708052725',
    projectId: 'l41l7cxww4q8mcv88ier1zchmqttxz',
    storageBucket: 'l41l7cxww4q8mcv88ier1zchmqttxz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbE9OjsU4lVyfpbCHuvO3crTToALsfPA',
    appId: '1:1011708052725:ios:416259f8be411dd4a4f1bc',
    messagingSenderId: '1011708052725',
    projectId: 'l41l7cxww4q8mcv88ier1zchmqttxz',
    storageBucket: 'l41l7cxww4q8mcv88ier1zchmqttxz.firebasestorage.app',
    androidClientId: '1011708052725-id44srkour49vocukfqve09i3oqcasqe.apps.googleusercontent.com',
    iosClientId: '1011708052725-ep0i2uhjnbpkbt613s4f95kue69te8dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
